name: Release Build

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: Windows-aarch64
            runs-on: windows-11-arm
            target: aarch64-pc-windows-msvc
    
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update CHANGELOG
        if: startsWith(github.ref, 'refs/tags/')
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          writeToFile: true

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        if: startsWith(github.ref, 'refs/tags/')
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: binwalk
          target: ${{ matrix.platform.target }}
          release-tag-prefix: v
          changes-file: "CHANGELOG.md"          
          action-gh-release-parameters: |
            {
              "draft": false,
              "prerelease": false,
              "overwrite": true,
              "generate_release_notes": true,
              "make_latest": true,
              "body_path": "CHANGELOG.md",
              "token": "${{ secrets.GITHUB_TOKEN }}"
            }
      - name: Commit CHANGELOG.md
        if: startsWith(github.ref, 'refs/tags/')
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
        